fix which modals to show, fix the user dsr balance calcs
makerdao-dux/metadao-frontend pull request #105
Opened 2023-04-14 23:14 UTC by b-pmcg

### What does this PR do?
- fixes the conditionals to show modals on the DSR page
- fixes the userDsrBalance calculation

2023-04-17 05:03 UTC, rafinskipg requested changes
I think we should figure out how do we return numbers from the hooks package in the same way accross all the responses, so we avoid having a mix of bigints and BigNumbers

2023-04-17 05:03 UTC, rafinskipg commented on apps/webapp/src/modules/dsr/components/DsrWithdrawModal.tsx
> +            balance={parseUnits(formatRay(dsrData?.userDsrBalance).toString()) || BigNumber.from(0)}
why do we need to do this? what are the decimal places of userDsrBalance? is not 18?

2023-04-17 22:21 UTC, b-pmcg commented
> I think we should figure out how do we return numbers from the hooks package in the same way accross all the responses, so we avoid having a mix of bigints and BigNumbers

@rafinskipg yeah good point, I think we should migrate away from ethers v5 since wagmi will soon be using bigints. I'll bring this up in the discord so all the devs can discuss.

2023-04-18 19:45 UTC, b-pmcg commented on apps/webapp/src/modules/dsr/components/DsrWithdrawModal.tsx
> +            balance={parseUnits(formatRay(dsrData?.userDsrBalance).toString()) || BigNumber.from(0)}
yeah the dsrBalance is stored as a `ray` with 27 decimal places, so we have to convert it. When we are eventually able to move away from using bignumbers we won't have to do this conversion.

2023-04-19 06:56 UTC, rafinskipg commented on apps/webapp/src/modules/dsr/components/DsrDepositModal.tsx
> +      setHasAllowance(true);
`setHasAllowance(allowance.gte(depositAmount))` this makes it in one line

2023-04-19 06:56 UTC, rafinskipg commented on apps/webapp/src/modules/dsr/components/DsrWithdrawModal.tsx
> +            balance={parseUnits(formatRay(dsrData?.userDsrBalance).toString()) || BigNumber.from(0)}
this is a bit crazy.. 🦗 

We should aim for tokenInput to accept directly whatever the hook returns, to avoid doing parse + format, we are doing 2 conversions there

2023-04-19 06:56 UTC, rafinskipg commented on apps/webapp/src/pages/Dsr.tsx
> +                          <StatNumber>{formatPercent(data.dsrApy)}</StatNumber>
👍

2023-04-19 06:56 UTC, rafinskipg commented on packages/utils/src/math.test.ts
> +    expect(rate).eq(expected);
nice

2023-04-19 07:03 UTC, rafinskipg approved these changes

2023-04-19 20:02 UTC, b-pmcg commented on apps/webapp/src/modules/dsr/components/DsrDepositModal.tsx
> +      setHasAllowance(true);
🧠

2023-04-19 20:07 UTC, merged