add hooks for total staked and calculate APR for farm
makerdao-dux/metadao-frontend pull request #116
Opened 2023-04-21 22:17 UTC by b-pmcg

### What does this PR do?

### Steps for testing:

### Screenshots (if relevant):

### Any additional helpful information?:

### Link to Shortcut ticket:

### Add a GIF:

2023-04-25 21:46 UTC, b-pmcg commented on packages/hooks/src/staking/useStakingRewardsApr.tsx
> +const daiUSDVal = ethers.BigNumber.from(1);
Without oracles contracts we have to hardcode these values. Not sure if this is the best place for it or not, but ultimately we will need to replace with the farms PIP contracts.

2023-04-26 07:08 UTC, tyler17 approved these changes

2023-04-26 08:09 UTC, torhector2 approved these changes
💯 LGTM

Just one minor comment.

2023-04-26 08:09 UTC, torhector2 commented on packages/hooks/src/staking/useStakingRewardsApr.tsx
> +  const isLoading = useMemo(() => {
no need to use `useMemo` with booleans

2023-04-26 10:34 UTC, adamgoth commented on apps/webapp/src/modules/farms/components/FarmItem.tsx
> +    address: ownerAddress,
A wallet connection (owner address here) is required in order to show an APR?

2023-04-26 10:34 UTC, adamgoth commented on apps/webapp/src/modules/farms/components/FarmMetrics.tsx
> +        {!!totalStaked && <Text>{formatAmount(totalStaked.toBigInt())}</Text>}
Should we have a loading skeleton or some placeholder if `totalStaked` doesn't exist?

2023-04-26 10:34 UTC, adamgoth commented on packages/hooks/src/staking/useStakingRewardsApr.tsx
> +  address?: Address;
Is this address value used somewhere? I don't see it being used but I could be overlooking it

2023-04-26 10:49 UTC, adamgoth reviewed
Minor thing but looks weird to see such a large number include decimals. Maybe we come up with a helper for formatting numbers.

Something as simple as
less than 100 = 2 decimals // ex `10.34% APR`
greater than 100 = 0 deicmals // ex `134% APR`, `2,899% APR`

<img width="141" alt="Screenshot 2023-04-26 at 12 45 45 PM" src="https://user-images.githubusercontent.com/5225766/234552717-bb0018f6-59a9-419a-a691-ac00e83fb355.png">

2023-04-26 12:47 UTC, rafinskipg requested changes
I'm unsure about the output of the APR i would like to understand it better

2023-04-26 12:47 UTC, rafinskipg commented on packages/utils/src/math.test.ts
> +
why are the numbers so big? What is the representation? 

Shouldn't it be something easier like "30" for 30%? 

i always get confused with this things with the big decimals.

2023-04-26 12:47 UTC, rafinskipg commented on packages/utils/src/math.ts
> +export const calculateApy = (apr: bigint): bigint => {
I added this, but i'm not sure this is correct, and it overflows when passing those bigints

2023-04-26 20:54 UTC, b-pmcg commented
> Minor thing but looks weird to see such a large number include decimals. Maybe we come up with a helper for formatting numbers.
> 
> Something as simple as less than 100 = 2 decimals // ex `10.34% APR` greater than 100 = 0 deicmals // ex `134% APR`, `2,899% APR`
> 
> <img alt="Screenshot 2023-04-26 at 12 45 45 PM" width="141" src="https://user-images.githubusercontent.com/5225766/234552717-bb0018f6-59a9-419a-a691-ac00e83fb355.png">

yeah, this makes sense. I started working on it a little bit, but it's actually pretty complicated, so I think it should be a separate ticket since it affects all numbers. The reason it's complicated is because `parseFloat` returns a number with an exponent in it if there are too many decimal places (eg `1.44e-11`) and doing gt/lt comparisons on this fails.

We can probably develop a better formatter that has a set of rules that the numbers filter through to get to the results we want.

2023-04-26 20:55 UTC, b-pmcg commented
accidentally click closed & comment 🤦

2023-04-26 20:58 UTC, b-pmcg commented on packages/utils/src/math.test.ts
> +
answered in the discord as well, but generally its because the values we get directly from the contract are bigints with 18 decimal places and I wanted to keep the math functions pure so they always deal with the values from the contracts. And the UI is able to convert the bigints to more human readable forms pretty easily.

2023-04-26 21:02 UTC, b-pmcg commented on packages/utils/src/math.ts
> +export const calculateApy = (apr: bigint): bigint => {
I think your math is correct, but I had the same issue with the overflows. I think using APR makes the most sense with our farms due to the reasons you mentioned.

2023-04-27 11:48 UTC, rafinskipg commented on packages/utils/src/math.test.ts
> +
so it doesn't matter if you send a numer with 18 decimals or just any number right? it will calculate the relative APRs correctly?

2023-04-27 12:20 UTC, rafinskipg approved these changes

2023-04-27 12:28 UTC, merged