Charts farms (WIP)
makerdao-dux/metadao-frontend pull request #130
Opened 2023-05-02 13:53 UTC by rafinskipg

- Adds recharts library 
- Adds new TVl metrics from the subdao subgraph
- Displaying charts for TVL / Deposits / Withdraws / Rewards over time (In progress)

2023-05-08 08:54 UTC, torhector2 requested changes
Everything looks very good, I requested changes mostly because of the date calculations I pointed above, I think they're wrong.

If you think that's correct I'll change the review.

2023-05-08 08:54 UTC, torhector2 commented on apps/webapp/src/modules/farms/helpers/parseFarmChartData.ts
> +  // For the last 30 days
One possible improvement could be to add more timeframes: 30 days, 3 months, 6 months, 1 year, All time. No need to be done now ofc, just a suggestion.

2023-05-08 08:54 UTC, torhector2 commented on apps/webapp/src/modules/farms/components/history/RewardsStats.tsx
> +  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, now.getDate());
When you do this in January the result for lastMonth is -1

2023-05-08 08:54 UTC, torhector2 commented on apps/webapp/src/modules/farms/components/history/RewardsStats.tsx
> +  const yesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
Same here when the day is the 1st, the result will be 0.

2023-05-08 08:54 UTC, torhector2 commented on apps/webapp/src/modules/farms/components/FarmDetail.tsx
>            <Card m={4}>
I think the FarmDetail component has grown to much and it's a good moment to move every Card into its own Component. It'll make it easier to read and follow.
```
<ManagePositionCard />
<RewardsCard />
...
```

2023-05-09 01:34 UTC, tyler17 commented
<img width="114" alt="Screen Shot 2023-05-08 at 6 33 49 PM" src="https://user-images.githubusercontent.com/3388550/236971878-9edbea9f-9788-4b27-8a73-3c38a8042f6c.png">
Also noticed DUXCOIN gets cut off on the Y axis here

2023-05-09 02:07 UTC, tyler17 approved these changes
Looks great to me, just left some minor comments

2023-05-09 02:07 UTC, tyler17 commented on apps/webapp/src/modules/farms/helpers/parseFarmChartData.ts
> +  // For the last 30 days
👍 we can add a TODO comment that says we're currently just grouping by day

2023-05-09 12:28 UTC, rafinskipg commented on apps/webapp/src/modules/farms/components/history/RewardsStats.tsx
> +  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, now.getDate());
changed to a timestamp

2023-05-09 12:28 UTC, rafinskipg commented on apps/webapp/src/modules/farms/helpers/parseFarmChartData.ts
> +  // For the last 30 days
updated

2023-05-09 12:45 UTC, rafinskipg commented on apps/webapp/src/modules/farms/components/history/DepositsWithdrawalsChart.tsx
> +            stroke={'#ADADAD'}
i think the colors are not definitive, i will ask tiago to provide a new palette once we have the new branding

2023-05-09 12:55 UTC, torhector2 approved these changes

2023-05-11 06:38 UTC, merged