Toast alert new design
makerdao-dux/metadao-frontend pull request #137
Opened 2023-05-05 15:12 UTC by torhector2

### ToDo
- Think and define colors in the config file

### Custom Toasts
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/440694/236497244-1a40fb14-40da-445b-901c-1335dad58c12.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/440694/236497304-88e8be82-7897-4a53-b27a-6c3b053f9985.png">

### Custom Alerts
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/440694/236497531-2ca43e2a-cd76-4ad0-bd1b-b0a8fce97b26.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/440694/236497582-5ff8cd34-408d-4966-992f-e4cd1d420592.png">

2023-05-05 21:23 UTC, b-pmcg commented
looks really good! The only thing that looks a little strange to me that the shorter alerts have the icon above the content, while the longer ones have it in the left margin. I know that how it is on the designs, but maybe we can ask Tiago if that's what he intended, or see if everyone else thinks it's fine.

I'm not totally familiar enough with Chakra yet to understand why we couldn't use the default chakra alert component with some different variants, but if its the only way then 👍

2023-05-05 21:24 UTC, b-pmcg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +export function useToast(options?: UseToastOptions): CustomToastFn {
maybe we should move this to `modules/ui/hooks/useToast.ts`

2023-05-06 16:30 UTC, torhector2 commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +export function useToast(options?: UseToastOptions): CustomToastFn {
Agree 👍

2023-05-09 13:14 UTC, rafinskipg requested changes
I'm not sure about some things, i'll wait for other devs input

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +      variant="maker"
i'm not sure we should keep naming things "maker"

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +  const { main, LeftIcon } = useAlertUIData(title, description, status === 'loading' ? 'info' : status, link);
why is this a hook ?

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +const getDescription = (description: React.ReactNode) =>
why we need this as functions? It could probably be inline

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +          {linkComponent}
i think this "linkComponetn" could just be a children component,

the "learn more" style link with the external icon it should be probably a "external  link" component that is reused accross the app, with the little arrow

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +          {linkComponent}
Not all the toasts will have a link . Example: "invalid network, change network to continue"

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/hooks/useToast.tsx
> +  link?: CustomLink;
i think accepting a children component maybe better than a "link" , but idk. what other devs think? Would it be weird?

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/config/default-config.ts
> +    successBackground: { default: '#F6FEF9' },
i think we will need to define the dark colors

2023-05-09 13:14 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +  const lighterColor = adjustColor(defaultConfig.colors[status as Status].default, 15);
is there a way to not use javascript and use ` filter: brightness(85%);` ?  idk if that would work

2023-05-09 14:11 UTC, torhector2 commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +      variant="maker"
right, any idea? "brand"?

2023-05-09 14:12 UTC, torhector2 commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +const getDescription = (description: React.ReactNode) =>
true, they were more complex before moving stuff into the theme. I can inline them.

2023-05-10 07:41 UTC, torhector2 commented on apps/webapp/src/modules/config/default-config.ts
> +    successBackground: { default: '#F6FEF9' },
I'll ask for them 👍

2023-05-10 07:43 UTC, torhector2 commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +      variant="maker"
As Deniz suggested we keep "maker" until a new brand is defined.

2023-05-10 09:55 UTC, torhector2 commented on apps/webapp/src/modules/ui/components/Alerts.tsx
> +  renderBottom?: (status: ToastProps['status']) => React.ReactNode;
I add this so we can define dynamic components based on the status in case we only know the status at runtime.

Not sure if it's helpful or weird.

2023-05-10 10:03 UTC, rafinskipg approved these changes
I'll approve but i would wait for @adamgoth  and @b-pmcg  to chip in, since they are the most experimented with chackra ui

2023-05-15 10:37 UTC, adamgoth commented on apps/webapp/src/modules/config/default-config.ts
> +    successBackground: { default: '#F6FEF9' },
There are a lot of other colors that still need dark definitions. I think we should just add a backlog ticket for it for Tiago to define and then for devs to implement.

2023-05-15 10:45 UTC, adamgoth approved these changes
lgtm, nice job -- I asked a question in our design channel to see if we can maybe remove all the "classic" toast/alert stuff

2023-05-15 14:19 UTC, merged