Eslint updates
makerdao-dux/metadao-frontend pull request #36
Opened 2023-01-26 13:10 UTC by adamgoth

Minor README updates

Updates to fix linting errors

2023-01-26 14:51 UTC, rafinskipg requested changes

2023-01-26 14:51 UTC, rafinskipg commented on apps/webapp/.eslintrc.json
> +    "@typescript-eslint/no-var-requires": "off",
i think we might need to move the eslint to the root project, and if the webapp has different eslint rules, extend it,

2023-01-26 14:51 UTC, rafinskipg commented on apps/webapp/package.json
> +    "cypress": "^12.4.0",
do we need cypress even we have synpress installed that is using cypress also?

I see synpress uses cypress 11 so installing the 12 also will add an additional dev dependency. Is it because typescript doesnt pick well some types?

2023-01-26 14:54 UTC, adamgoth commented on apps/webapp/package.json
> +    "cypress": "^12.4.0",
Yeah, couldn’t figure out how to get the types without doing that

2023-01-27 13:48 UTC, rafinskipg approved these changes

2023-01-30 13:31 UTC, rafinskipg requested changes

2023-01-30 13:38 UTC, adamgoth commented on apps/webapp/tests/e2e/specs/dsr.spec.ts
> +    cy.get('h2').contains('Manage').should('be.visible');
Good catch

2023-01-30 13:39 UTC, adamgoth commented on packages/hooks/src/dsr/useDsrWithdraw.ts
> +  const chainId = chain === 31337 || chain === 1337 ? 1 : chain;
Good catch, this was meant to be a temporary workaround

2023-02-01 07:09 UTC, merged