Add tokeninput, fix storybook
makerdao-dux/metadao-frontend pull request #47
Opened 2023-02-07 10:05 UTC by rafinskipg

Adds a token input that accepts decimals with commas or dots. Gives errors with negative numbers and returns always a bignumber.

This component is meant to be used with the UI for inputting tokens

2023-02-07 10:51 UTC, adamgoth requested changes
Can we hook it up to DSR so we can make sure everything works end-to-end and consider the bug resolved?

Happy to jump in and help get it over the line, but let me know your thoughts on other PR comments.

2023-02-07 10:51 UTC, adamgoth commented on apps/webapp/src/modules/ui/components/TokenInput.tsx
> +    <React.Fragment>
`<React.Fragment>` seems unneeded here. 

I think we might be able to wrap this in chakra's `FormControl` component and pass `errorInvalidFormat` to it. Then it will inherit the error styling and be consistent with other form elements.

2023-02-07 10:51 UTC, adamgoth commented on apps/webapp/src/modules/ui/components/TokenInput.tsx
> +        type="text"
Shouldn't this be `type="number"` for a token input?

Testing via storybook, it seems you can type anything in.

<img width="1323" alt="Screenshot 2023-02-07 at 11 46 25 AM" src="https://user-images.githubusercontent.com/5225766/217224383-60b1f4ac-41e5-4f13-ae1a-5f81f5319c22.png">
<img width="1310" alt="Screenshot 2023-02-07 at 11 47 21 AM" src="https://user-images.githubusercontent.com/5225766/217224388-d2a29838-6499-4d17-9cf3-64b463508df9.png">

2023-02-07 13:08 UTC, rafinskipg commented on apps/webapp/src/modules/ui/components/TokenInput.tsx
> +        type="text"
We can do type number, but then it won't allow to add comas or dots at the same time, only numbers (which i think is fine too), first implementation i did allowed only for numbers

2023-02-07 13:08 UTC, rafinskipg commented
> Can we hook it up to DSR so we can make sure everything works end-to-end and consider the bug resolved?
> 
> Happy to jump in and help get it over the line, but let me know your thoughts on other PR comments.

Oki, I'll add it tomorrow morning

2023-02-08 10:01 UTC, adamgoth approved these changes
LGTM, this feels much better using BigNumber

I just swapped out the helper text for error text on the error message and added `formatUnits` to a few more places in the modals that needed it

2023-02-08 10:11 UTC, merged