Update e2e tests for the new pages
makerdao-dux/metadao-frontend pull request #68
Opened 2023-03-01 10:29 UTC by torhector2

E2E tests didn't pass due to some changes on the app's pages.
This PR updates the tests to make the tests pass. 

We could add more functionality to the tests if needed (maybe mock the delegates request to make it response always the same number of results), but my purpose with this PR was to set the test up and running again.

2023-03-01 16:40 UTC, rafinskipg requested changes

2023-03-01 16:40 UTC, rafinskipg commented on apps/webapp/tests/e2e/specs/delegates.spec.ts
> +        cy.get('[data-testid="delegate-card"]').should('have.length', 27);
it shouldn't be like that. Delegates should load 10 by 10, do not load 27 and then 54. If that is happening, something is wrong

2023-03-01 17:25 UTC, adamgoth commented on apps/webapp/tests/e2e/specs/delegates.spec.ts
> +        cy.get('[data-testid="delegate-card"]').should('have.length', 27);
I changed it to 27 so this is actually correct

2023-03-01 17:26 UTC, adamgoth approved these changes
Thanks for fixing these

2023-03-02 03:28 UTC, torhector2 commented on apps/webapp/tests/e2e/specs/delegates.spec.ts
> +        cy.get('[data-testid="delegate-card"]').should('have.length', 27);
Merging the branch as it seems to be the correct behaviour. Merging by checking the "Merge without waiting for requirements to be met (bypass branch protections)" option.

2023-03-02 03:29 UTC, merged