Wagmi cli
makerdao-dux/metadao-frontend pull request #85
Opened 2023-03-28 23:04 UTC by b-pmcg

### What does this PR do?
- uses wagmi cli to generate abis and address config helpers
- replaces instances of using contracts constant with the generated ones

2023-03-29 07:06 UTC, rafinskipg commented on apps/webapp/package.json
> +    "wagmi": "^0.12.7"
this has been updated in another PR, the one from hector, we updated the wagmi deps

2023-03-29 07:09 UTC, rafinskipg requested changes
We need to find a better way to interface with the contracts so all the types are exported correctly. 

- Group by chain (idk if that is already the case)
- Remove all the old contracts and references

2023-03-29 07:09 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyBuild.ts
> +    address: address[chainId as keyof typeof address],
we need the types to be exported correctly without having to do keyof typeof,

2023-03-29 07:09 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  const { address: contractAddress, abi } = proxyRegistryConfig;
can we have the contracts grouped by chain like before?

2023-03-29 07:09 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  const chainId = useChainId() as keyof typeof contractAddress;
also, we shouldn't need to do this

2023-03-29 14:43 UTC, b-pmcg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  const chainId = useChainId() as keyof typeof contractAddress;
yeah it sucks :(

2023-03-29 23:08 UTC, b-pmcg commented on packages/hooks/src/dsProxy/useDsProxyBuild.ts
> +    address: address[chainId as keyof typeof address],
This was because the keys of the address object are readonly and we could not use `chainId`, a number to key off them. I added `parseConfigForChain` which parses the address correctly without using `keyof typeof`.

2023-03-29 23:11 UTC, b-pmcg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  const { address: contractAddress, abi } = proxyRegistryConfig;
We can now get the contract by chain ID by using either `getAddressByChainId(addressGroup, chainId)` or `parseConfigForChain(contractConfig, chainId)` depending on the need. The generated file groups chainId's within the address object rather than the other way around.

2023-03-30 05:50 UTC, rafinskipg requested changes

2023-03-30 05:50 UTC, rafinskipg commented on packages/contracts/src/index.ts
> +  if (Object.hasOwn(addressGroup, chainId)) {
I don't think we need any of these helpers, if addressGroup is already an object with chainId inside we can access directly

2023-03-30 05:50 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  const contractAddress = getAddressByChainId(contractAddresses, chainId);
so we could just do `contractAddresses[chainId]` ? I thinkt hat would be more neat

2023-03-30 05:50 UTC, rafinskipg commented on packages/hooks/src/dsr/useChi.ts
> +  const { address: contractAddress, abi } = parseConfigForChain(mcdPotConfig, chainId);
same `mcdPotConfig.address[chainId]` would be enough right? no need to import another function to access a contract information. 

I think the contracts package should export things easily and ready to use.

2023-03-30 06:30 UTC, torhector2 commented on packages/contracts/src/index.ts
> +  if (Object.hasOwn(addressGroup, chainId)) {
Although I agree with what Rafa says in terms of usability, I can see it doesn't compile due to the readonly-ness of the generated types. We can try to find a different approach to export the generated types or use the helpers.

2023-03-30 07:07 UTC, torhector2 commented on packages/hooks/src/dsr/useChi.ts
> +  const { address: contractAddress, abi } = parseConfigForChain(mcdPotConfig, chainId);
In order to work you need to access like this :S

`mcdPotConfig.address[chainId as 1 | 5];`

2023-03-30 08:33 UTC, adamgoth commented
> When I connect my wallet on the DSR page, I get an error that crashes the page. The error message seems be "execution reverted" which isn't super helpful. I'll try to do a little more debugging locally.

It only appears to happen on goerli and not mainnet

2023-04-03 07:28 UTC, rafinskipg approved these changes
This looks neat 

I pretty much approve this approach

2023-04-03 07:28 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyBuild.ts
> +  const { config, refetch } = usePrepareProxyRegistryWrite({
love this

2023-04-03 07:28 UTC, rafinskipg commented on packages/hooks/src/dsProxy/useDsProxyData.ts
> +  } = useProxyRegistryRead({ functionName: 'proxies', args: [acct], enabled: acct !== ZERO_ADDRESS });
nice

2023-04-03 07:28 UTC, rafinskipg commented on packages/hooks/src/dsr/useChi.ts
> +  const { address: contractAddress } = useMcdPot();
so clean

2023-04-03 07:28 UTC, rafinskipg commented on packages/hooks/src/dsr/usePie.ts
> +  const { data, isLoading, error, refetch } = useMcdPotRead({ functionName: 'Pie' });
nice

2023-04-03 07:28 UTC, rafinskipg commented on packages/hooks/src/network/useChainId.ts
> +  Object.freeze(ret);
i don't understand why we need this?

2023-04-03 08:22 UTC, merged