Basic layout for detail pages
makerdao-dux/metadao-frontend pull request #89
Opened 2023-04-03 07:46 UTC by torhector2

Creates a basic layout for detail pages.

Desktop
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/440694/229444446-277a1de0-d976-470d-9e1f-7be3ce00ea9c.png">

Mobile
<img width="624" alt="image" src="https://user-images.githubusercontent.com/440694/229444507-9890a8d1-ef66-4800-bc19-e5189bef0705.png">

2023-04-03 14:50 UTC, rafinskipg commented
@torhector2 mhh i don't know if we need a generic layout for detail pages, is this repeated through the app? 

otherwise i think just define the styles on the delegate page

2023-04-03 14:59 UTC, torhector2 commented
@rafinskipg there was this ticket where it was suggested that
https://app.shortcut.com/dux-makerdao/story/1991/create-a-layout-component-for-the-different-profile-pages

2023-04-04 04:42 UTC, rafinskipg requested changes

2023-04-04 04:42 UTC, rafinskipg commented on apps/webapp/src/modules/layout/components/detail-layout/LeftSection.tsx
> +  return (
i don't think we need to create this component, is just a div, better just leave it on the detaillayout

2023-04-04 04:42 UTC, rafinskipg commented on apps/webapp/src/modules/layout/components/detail-layout/MainSection.tsx
> +    <Box as="main" overflowY="auto" sx={sx}>
i don't think we need to create this component, is just a div, better just leave it on the detaillayout

2023-04-04 08:27 UTC, torhector2 commented on apps/webapp/src/modules/layout/components/detail-layout/MainSection.tsx
> +    <Box as="main" overflowY="auto" sx={sx}>
@rafinskipg made those changes

2023-04-05 10:57 UTC, rafinskipg approved these changes

2023-04-06 06:01 UTC, merged